export const colors = {
  bg:           "#f8fafc",
  bgCard:       "#ffffff",
  bgSidebar:    "#1e293b",
  border:       "#e2e8f0",
  borderDark:   "#cbd5e1",
  textPrimary:  "#0f172a",
  textSecondary:"#475569",
  textMuted:    "#94a3b8",
  blue:         "#2563eb",
  blueHover:    "#1d4ed8",
  blueLight:    "#eff6ff",
  green:        "#16a34a",
  greenLight:   "#f0fdf4",
  greenBorder:  "#bbf7d0",
  red:          "#dc2626",
  redLight:     "#fef2f2",
  redBorder:    "#fecaca",
  yellow:       "#d97706",
  yellowLight:  "#fffbeb",
  yellowBorder: "#fde68a",
  purple:       "#7c3aed",
  purpleLight:  "#f5f3ff",
};

export const shared = {
  card: {
    background:   "#ffffff",
    border:       "1px solid #e2e8f0",
    borderRadius: 12,
    padding:      24,
    marginBottom: 20,
    boxShadow:    "0 1px 3px rgba(0,0,0,0.06)",
  },
  input: {
    width:        "100%",
    padding:      "10px 14px",
    fontSize:     14,
    borderRadius: 8,
    border:       "1px solid #e2e8f0",
    background:   "#ffffff",
    color:        "#0f172a",
    outline:      "none",
    boxSizing:    "border-box",
    transition:   "border-color 0.15s",
  },
  label: {
    display:      "block",
    fontSize:     13,
    fontWeight:   600,
    color:        "#374151",
    marginBottom: 6,
  },
  formRow: {
    display:      "flex",
    flexDirection:"column",
    gap:          6,
    marginBottom: 18,
  },
  btn: (variant = "primary") => ({
    padding:      "10px 20px",
    fontSize:     14,
    fontWeight:   600,
    borderRadius: 8,
    border:       "none",
    cursor:       "pointer",
    transition:   "all 0.15s",
    background:   variant === "primary"  ? "#2563eb"
                : variant === "success"  ? "#16a34a"
                : variant === "danger"   ? "#dc2626"
                : variant === "warning"  ? "#d97706"
                : variant === "outline"  ? "#ffffff"
                : "#f1f5f9",
    color:        variant === "outline"  ? "#374151" : "#ffffff",
    border:       variant === "outline"  ? "1px solid #e2e8f0" : "none",
  }),
  select: {
    width:        "100%",
    padding:      "10px 14px",
    fontSize:     14,
    borderRadius: 8,
    border:       "1px solid #e2e8f0",
    background:   "#ffffff",
    color:        "#0f172a",
    outline:      "none",
    cursor:       "pointer",
  },
  errorBox: {
    background:   "#fef2f2",
    border:       "1px solid #fecaca",
    borderRadius: 8,
    padding:      "12px 16px",
    color:        "#dc2626",
    fontSize:     13,
    marginTop:    12,
  },
  successBox: {
    background:   "#f0fdf4",
    border:       "1px solid #bbf7d0",
    borderRadius: 8,
    padding:      16,
    color:        "#15803d",
    fontSize:     13,
    marginTop:    12,
  },
};
